-- LPM Database Schema
-- Complete schema initialization for production deployment
-- This script creates all tables and constraints required by the application

create table activity_log (
    created_at timestamp(6) not null,
    entityId bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    user_id bigint,
    action varchar(50) not null,
    entityType varchar(100) not null,
    details varchar(255),
    primary key (id)
);

create table comment (
    author_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    ticket_id bigint not null,
    updated_at timestamp(6) not null,
    content TEXT not null,
    primary key (id)
);

create table project (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    owner_id bigint not null,
    status_id bigint,
    updated_at timestamp(6) not null,
    projectKey varchar(10) not null unique,
    description varchar(255),
    name varchar(255) not null,
    primary key (id)
);

create table project_member (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    role varchar(50) not null,
    primary key (id),
    unique (project_id, user_id)
);

create table project_status (
    "order" integer,
    color varchar(7),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    icon varchar(50),
    name varchar(100) not null unique,
    description varchar(500),
    primary key (id)
);

create table role (
    "order" integer,
    color varchar(7),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    icon varchar(50),
    name varchar(50) not null unique,
    description varchar(500),
    primary key (id)
);

create table ticket (
    assignee_id bigint,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    priority_id bigint,
    project_id bigint not null,
    reporter_id bigint not null,
    status_id bigint,
    type_id bigint,
    updated_at timestamp(6) not null,
    ticketKey varchar(20) not null unique,
    description varchar(255),
    title varchar(255) not null,
    primary key (id)
);

create table ticket_priority (
    "order" integer,
    color varchar(7),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    icon varchar(50),
    name varchar(100) not null unique,
    description varchar(500),
    primary key (id)
);

create table ticket_status (
    "order" integer,
    color varchar(7),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    icon varchar(50),
    name varchar(100) not null unique,
    description varchar(500),
    primary key (id)
);

create table ticket_type (
    color varchar(7),
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    icon varchar(50),
    name varchar(100) not null unique,
    description varchar(500),
    primary key (id)
);

create table "user" (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    username varchar(50) not null unique,
    display_name varchar(100) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    status varchar(255) not null check ((status in ('ACTIVE','INACTIVE','LOCKED'))),
    primary key (id)
);

create table user_role (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

alter table if exists activity_log 
    add constraint FK5sg44eahhxg26b56wes4tsc7u 
    foreign key (user_id) 
    references "user";

alter table if exists comment 
    add constraint FKrhy3r0t23ktix2xv13vri24n3 
    foreign key (author_id) 
    references "user";

alter table if exists comment 
    add constraint FKsyf8wt2qb7rhcau6v3p4axrba 
    foreign key (ticket_id) 
    references ticket;

alter table if exists project 
    add constraint FKb761xcqb5j11pbulfbrij8wmw 
    foreign key (owner_id) 
    references "user";

alter table if exists project 
    add constraint FK89ii0bpi6xcc0y8c18cq3lb1n 
    foreign key (status_id) 
    references project_status;

alter table if exists project_member 
    add constraint FK103dwxad12nbaxtmnwus4eft2 
    foreign key (project_id) 
    references project;

alter table if exists project_member 
    add constraint FKg52l1e32htqaytsis91bi4j35 
    foreign key (user_id) 
    references "user";

alter table if exists ticket 
    add constraint FKi8v5xadyxrfg4bt3q1vfsfl1w 
    foreign key (assignee_id) 
    references "user";

alter table if exists ticket 
    add constraint FKmmequa4stgwnwo65p16g4g9vg 
    foreign key (priority_id) 
    references ticket_priority;

alter table if exists ticket 
    add constraint FKon3g4edms44nvfti4skwns3vn 
    foreign key (project_id) 
    references project;

alter table if exists ticket 
    add constraint FKfb2gy0ta5y9wmlswwtsj57fbp 
    foreign key (reporter_id) 
    references "user";

alter table if exists ticket 
    add constraint FKf5v1wmegho829dbtu7t2pwm1q 
    foreign key (status_id) 
    references ticket_status;

alter table if exists ticket 
    add constraint FKnk40xmmqnx78naomux703i9vs 
    foreign key (type_id) 
    references ticket_type;

alter table if exists user_role 
    add constraint FKa68196081fvovjhkek5m97n3y 
    foreign key (role_id) 
    references role;

alter table if exists user_role 
    add constraint FKfgsgxvihks805qcq8sq26ab7c 
    foreign key (user_id) 
    references "user";

INSERT INTO role (name, description, color, icon, "order", created_at, updated_at) VALUES ('ADMIN', 'System administrator with full access', '#FF0000', 'shield', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('PROJECT_MANAGER', 'Project lead with project management permissions', '#0000FF', 'briefcase', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('DEVELOPER', 'Team member with ticket creation and editing', '#00AA00', 'code', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('VIEWER', 'Read-only access to projects and tickets', '#999999', 'eye', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;
INSERT INTO "user" (username, email, password_hash, display_name, status, created_at, updated_at) VALUES ('admin', 'admin@lpm.local', 'bHBtZGV2c2FsdDEyMzQ1Njc4OTA=:1+UXcFhT3b+FyQrAtXaH9nrBwGc2MHOo6vat9EEXtPI=', 'Administrator', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('manager', 'manager@lpm.local', 'bHBtZGV2c2FsdDEyMzQ1Njc4OTA=:mhtdft2mhgY2TyOtHK9zm/CZFsHoVg1SxdQCT8CWQTk=', 'Project Manager', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), ('developer', 'developer@lpm.local', 'bHBtZGV2c2FsdDEyMzQ1Njc4OTA=:HciRvYkm9aY+oit7mtFAH8PvDEuRsN9Bdi+bFAypk0g=', 'Developer', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;
INSERT INTO user_role (user_id, role_id)  SELECT u.id, r.id FROM "user" u, role r  WHERE u.username = 'admin' AND r.name = 'ADMIN' ON CONFLICT DO NOTHING;
INSERT INTO user_role (user_id, role_id)  SELECT u.id, r.id FROM "user" u, role r  WHERE u.username = 'manager' AND r.name = 'PROJECT_MANAGER' ON CONFLICT DO NOTHING;
INSERT INTO user_role (user_id, role_id)  SELECT u.id, r.id FROM "user" u, role r  WHERE u.username = 'developer' AND r.name = 'DEVELOPER' ON CONFLICT DO NOTHING;
